import { Category, AdviceData } from './types';

export const CATEGORY_EMOJI_CODES: Record<Category, string> = {
  [Category.Finance]: "1f4b8",
  [Category.Love]: "1f498",
  [Category.Health]: "1f9d8",
  [Category.Social]: "1f942",
  [Category.Work]: "1f4bc",
  [Category.SelfCare]: "1f6c1",
  [Category.Family]: "1f3e1",
  [Category.DailyHabits]: "1f5d3-fe0f",
  [Category.Friends]: "1f46f",
  [Category.DigitalLife]: "1f4f1",
};

export const ADVICE_DATABASE: AdviceData = {
  [Category.Finance]: [
    "Check your subscriptions once a month. One of them is stealing from you.",
    "Don’t shop online when you’re bored. That’s how regret gets delivered.",
    "If you can’t buy it twice, think longer before buying it once.",
    "Unsubscribe before you forget why you signed up.",
    "Track your spending for one week. You’ll spot the leak immediately.",
    "Cheap chargers always fail at the worst time. Spend a little more.",
    "Avoid impulse buys after midnight. Nothing good happens after midnight.",
    "Set spending limits before you feel rich.",
    "Sales are only savings if you planned to buy it anyway.",
    "Delete shopping apps you only use when you’re stressed.",
    "Check bank statements like you check social media. Regularly.",
    "Don’t loan money you’ll resent not getting back.",
    "Keep an emergency fund even if it grows slowly.",
    "Pause before tapping “Buy now”. Even 10 seconds helps.",
    "Avoid lifestyle upgrades that lock you into higher monthly bills.",
    "Don’t compare your salary to someone else’s highlight reel.",
    "If a deal feels rushed, walk away.",
    "Buy quality for things you use every day.",
    "Review your subscriptions on your birthday. Make it a ritual.",
    "Money saved quietly is still money saved.",
    "Avoid financial decisions when you’re emotional.",
    "Pay yourself first, even if it’s small.",
    "Set reminders for bills so fees don’t sneak up on you.",
    "Don’t keep unused cards “just in case”.",
    "If it requires a payment plan, think twice.",
    "Track expenses before setting strict budgets. Awareness comes first.",
    "Avoid shopping as entertainment.",
    "Cancel trials immediately after signing up.",
    "Don’t keep money goals vague. Numbers matter.",
    "Raise your savings when your income increases, not your lifestyle.",
    "Avoid lending money to fix guilt.",
    "Save windfalls before spending them.",
    "Revisit old subscriptions you forgot existed.",
    "If you dread checking your balance, that’s your cue.",
    "Avoid expensive habits that don’t bring daily value.",
    "Plan big purchases in advance. Anticipation beats regret.",
    "Don’t shop hungry, tired, or bored.",
    "Keep a “fun money” limit to avoid guilt spending.",
    "Stop paying for convenience you don’t need.",
    "Automate savings so you don’t negotiate with yourself.",
    "If it needs constant maintenance, it costs more than you think.",
    "Review your spending categories every few months.",
    "Keep receipts for big purchases until you’re sure.",
    "Avoid subscriptions that rely on forgetfulness.",
    "Money anxiety often comes from not knowing the numbers.",
    "Set clear savings goals, not vague intentions.",
    "Don’t upgrade something that still works fine.",
    "Avoid emotional shopping after bad days.",
    "If it doesn’t fit your budget now, it won’t fit later.",
    "Re-evaluate recurring payments quarterly.",
    "Spending less can feel better than earning more.",
    "Avoid flashy investments you don’t understand.",
    "Keep separate accounts for saving and spending.",
    "Small daily expenses add up faster than you think.",
    "Don’t ignore fees. They quietly compound.",
    "Financial discipline beats motivation.",
    "Budget for joy, not just survival.",
    "Track money weekly, not yearly.",
    "Avoid impulse upgrades pushed by “limited time” banners.",
    "Keep emergency money boring and accessible.",
    "If you can’t explain the purchase, don’t make it.",
    "Don’t shop to impress people who won’t notice.",
    "Compare prices before loyalty kicks in.",
    "Avoid buying things to fix boredom.",
    "Save for future peace, not future stress.",
    "Review subscriptions every season change.",
    "Avoid spending money to escape uncomfortable emotions.",
    "Know your fixed costs by heart.",
    "Financial clarity reduces anxiety more than extra income.",
    "Spend intentionally, not reactively.",
    "Delay purchases that excite you too quickly.",
    "Track cash leaks, not just big expenses.",
    "Avoid “treat yourself” spirals.",
    "Check return policies before buying.",
    "Separate wants from timing. You can want it later.",
    "Set a monthly money check-in with yourself.",
    "Avoid upgrades that don’t solve real problems.",
    "Stop paying for tools you don’t use.",
    "Revisit your financial goals when life changes.",
    "Avoid debt for things that lose value quickly.",
    "Save before spending, not after.",
    "Watch your money habits during stressful weeks.",
    "Avoid keeping cards linked to unused services.",
    "If you forget what you bought, you didn’t need it.",
    "Money saved is future flexibility.",
    "Avoid impulse purchases disguised as “self-care”.",
    "Don’t normalize small overdraft fees.",
    "Set spending alerts to stay aware.",
    "Reduce recurring costs before chasing extra income.",
    "Avoid buying trends you won’t love long-term.",
    "Track expenses by category to spot patterns.",
    "Avoid financial advice that promises shortcuts.",
    "Plan purchases, don’t chase deals.",
    "Keep financial goals visible, not hidden.",
    "Money habits matter more than money moments.",
    "Cancel services you haven’t used in 30 days.",
    "Avoid spending to fill emotional gaps.",
    "Review financial goals every quarter.",
    "Spend money where it truly improves your daily life.",
    "Financial peace comes from clarity, not perfection."
  ],
  [Category.Love]: [
    "Don’t text when you’re hungry, tired, or already annoyed.",
    "If they confuse you often, that’s information.",
    "Pay attention to how you feel after spending time with them.",
    "Ask questions you’re afraid of the answers to.",
    "Consistency matters more than intensity.",
    "Don’t chase mixed signals. Clarity is kinder.",
    "If they only show up late at night, notice that pattern.",
    "Say what you mean instead of hoping they guess.",
    "Chemistry fades if communication doesn’t follow.",
    "Don’t stay just because you’ve already stayed this long.",
    "How they handle small conflicts matters more than big promises.",
    "Don’t explain your needs like you’re apologizing.",
    "If you feel lonely with them, that’s not a good sign.",
    "Attraction grows where respect lives.",
    "Stop rereading old messages. They won’t change.",
    "Love shouldn’t feel like a performance review.",
    "If effort disappears after commitment, talk about it.",
    "Notice how they talk about people they used to love.",
    "Don’t ignore your body’s reactions. They’re honest.",
    "Choose someone who listens without planning their reply.",
    "Don’t rush closeness to avoid loneliness.",
    "Pay attention to actions, not explanations.",
    "If you’re always adjusting, ask why.",
    "Love shouldn’t make you shrink.",
    "Ask for what you need, not what you think they’ll accept.",
    "If you feel anxious most of the time, pause.",
    "Don’t confuse familiarity with safety.",
    "How someone handles boundaries tells you a lot.",
    "You shouldn’t have to earn basic kindness.",
    "Love grows when both people feel seen.",
    "Don’t stay silent to keep the peace.",
    "If you’re scared to bring things up, notice that.",
    "Pay attention to how they show care on ordinary days.",
    "Love isn’t proven through endurance.",
    "Choose someone who makes repairs after mistakes.",
    "Don’t settle because you’re tired of starting over.",
    "Your needs are not “too much.”",
    "Don’t romanticize emotional unavailability.",
    "Healthy love feels calm more often than chaotic.",
    "Trust builds slowly and breaks quickly.",
    "If you feel like you’re competing for attention, stop.",
    "Ask how they imagine the future. Listen closely.",
    "Love shouldn’t require constant reassurance.",
    "Notice whether conflict leads to growth or distance.",
    "Don’t ignore red flags because they wave politely.",
    "Choose honesty over harmony.",
    "Love is mutual effort, not mutual exhaustion.",
    "If they dismiss your feelings, believe them.",
    "Don’t wait for someone to change who hasn’t tried.",
    "You deserve enthusiasm, not tolerance.",
    "Attraction without respect won’t last.",
    "Love shouldn’t feel like guessing.",
    "If you feel calmer alone, ask why.",
    "Don’t confuse potential with reality.",
    "Healthy love allows room for individuality.",
    "Pay attention to how disagreements end.",
    "Choose someone who’s curious about your inner world.",
    "Love grows where accountability lives.",
    "If you’re afraid to be yourself, something’s off.",
    "Don’t stay because you’re scared of being alone.",
    "Love shouldn’t feel like walking on eggshells.",
    "Notice how they respond when you’re vulnerable.",
    "If they avoid difficult conversations, that matters.",
    "Love thrives on mutual respect, not power imbalance.",
    "Don’t ignore your intuition to keep hope alive.",
    "Choose growth over comfort.",
    "Love should feel supportive, not draining.",
    "If communication feels one-sided, it probably is.",
    "Don’t stay where effort feels conditional.",
    "Love is shown in follow-through.",
    "Don’t beg for attention that should be given freely.",
    "If they don’t make time, they’re making a choice.",
    "Love shouldn’t require constant explanation of your worth.",
    "Notice whether you feel valued or evaluated.",
    "Choose emotional safety over excitement.",
    "Love grows through repair, not perfection.",
    "If they invalidate your feelings, don’t minimize that.",
    "Love shouldn’t feel like survival.",
    "Choose someone who communicates, not disappears.",
    "If it hurts more than it heals, pause.",
    "Love doesn’t demand you abandon yourself.",
    "Pay attention to patterns, not apologies.",
    "Healthy love includes boundaries.",
    "Don’t stay in confusion longer than necessary.",
    "Love should feel like partnership, not performance.",
    "Choose someone who respects your time.",
    "Love grows in clarity, not ambiguity.",
    "Don’t stay for memories if the present hurts.",
    "You deserve to feel chosen.",
    "Love shouldn’t feel like constant negotiation.",
    "If you feel unseen, speak up or step back.",
    "Choose someone who makes space for your feelings.",
    "Love isn’t proven by how much you endure.",
    "Pay attention to emotional consistency.",
    "Don’t ignore discomfort just because you care.",
    "Love should add peace, not anxiety.",
    "If they don’t listen, stop explaining.",
    "Choose reciprocity over longing.",
    "Love thrives where effort is mutual.",
    "If it feels heavy most days, reconsider."
  ],
  [Category.Health]: [
    "Drink water before coffee. Your body notices.",
    "Stretch your back before checking your phone in the morning.",
    "If you’re tired all the time, sleep is the first suspect.",
    "Go outside once a day, even briefly.",
    "Eat slower than you think you should.",
    "If your shoulders are tight, unclench your jaw too.",
    "Rest before you feel exhausted.",
    "Walk when your thoughts start looping.",
    "Your body needs movement, not punishment.",
    "Don’t skip meals to feel productive.",
    "Headaches are often dehydration in disguise.",
    "Sleep is not optional maintenance.",
    "Stretching counts even if it’s only two minutes.",
    "If you feel irritable, check when you last ate.",
    "Breathe through your nose when you can.",
    "Stop scrolling before bed. Your nervous system needs quiet.",
    "Sitting too long shows up later. Stand up now.",
    "Go to bed at the same time more often than not.",
    "Gentle consistency beats intense bursts.",
    "Your body isn’t lazy. It’s communicating.",
    "Don’t ignore small aches that keep returning.",
    "Eat vegetables you actually enjoy.",
    "If your neck hurts, check your screen height.",
    "Take breaks before your body forces one.",
    "A short walk is still a win.",
    "Drink water when you feel foggy.",
    "Don’t power through pain just to finish a task.",
    "Sleep debt compounds quietly.",
    "Move your body before your mind talks you out of it.",
    "If your breathing is shallow, slow it down.",
    "Your posture affects your mood more than you think.",
    "Get sunlight early in the day if possible.",
    "Don’t treat rest like a reward.",
    "Stretch areas that feel “fine” too.",
    "Eat without distractions sometimes.",
    "If your eyes hurt, look far away for a minute.",
    "Fatigue is information, not failure.",
    "Your body likes routines.",
    "Stand up and shake out tension occasionally.",
    "Pain is not weakness leaving the body.",
    "Sleep solves more problems than supplements.",
    "If you’re always stiff, move more gently, not harder.",
    "Drink water before assuming you need sugar.",
    "Regular meals stabilize your energy.",
    "Breathe deeply when stress spikes.",
    "Stop holding your breath during stressful moments.",
    "Your body responds to kindness faster than force.",
    "Stretch after sitting, not just after workouts.",
    "If you’re sore every day, reassess intensity.",
    "Consistency matters more than perfection.",
    "Take recovery days seriously.",
    "Eat protein regularly, not just occasionally.",
    "If your sleep is off, check caffeine timing.",
    "Move your spine daily in some way.",
    "Health isn’t built in extremes.",
    "If you feel dizzy, pause and ground yourself.",
    "Your body needs fuel to function well.",
    "Don’t skip warm-ups.",
    "Gentle walks count as exercise.",
    "Listen when your body asks for rest.",
    "Avoid long stretches without movement.",
    "Drink water before reaching for painkillers.",
    "Stretch areas you tense when stressed.",
    "Sleep improves decision-making more than willpower.",
    "Eat until satisfied, not stuffed.",
    "Your body prefers regular sleep patterns.",
    "If you feel stiff in the morning, move gently.",
    "Health improves with small daily habits.",
    "Take deep breaths when anxiety show up physically.",
    "Recovery is part of progress.",
    "If your energy crashes daily, review your meals.",
    "Stretch your hips if you sit a lot.",
    "Hydration affects focus more than you expect.",
    "Don’t ignore recurring pain just because it’s mild.",
    "Move your body even on low-motivation days.",
    "Rest days prevent injuries.",
    "Your body adapts to what you do repeatedly.",
    "Breathe slower when stressed.",
    "Health improves when routines stabilize.",
    "Listen to discomfort before it becomes pain.",
    "Eat foods that make you feel good afterward.",
    "Stretch gently before sleep.",
    "Your body needs consistency, not perfection.",
    "Stop pushing when pain sharpens.",
    "Recovery speeds progress.",
    "Drink water when you wake up.",
    "Stretch your chest if your shoulders round forward.",
    "Health habits stack over time.",
    "If you feel tense, move slowly.",
    "Prioritize sleep like an appointment.",
    "Gentle movement is still movement.",
    "Pain is feedback, not failure.",
    "If you feel off, check sleep, food, and water first.",
    "Your body responds best to patience.",
    "Stretch tight muscles daily.",
    "Avoid ignoring stress signals in your body.",
    "Health isn’t built overnight.",
    "Small habits done daily add up.",
    "Treat your body like it’s on your side.",
    "Consistent care beats occasional extremes."
  ],
  [Category.Social]: [
    "Listen without planning your reply.",
    "Put your phone away when someone is opening up.",
    "Leave gatherings while you still have energy.",
    "Don’t over-explain yourself to be liked.",
    "Notice who asks follow-up questions.",
    "Say people’s names when you greet them.",
    "Give compliments without expecting one back.",
    "Pause before responding in heated conversations.",
    "Not every message needs an immediate reply.",
    "Eye contact matters more than perfect words.",
    "Let silence breathe instead of filling it.",
    "Ask open-ended questions.",
    "Don’t interrupt to relate. Listen first.",
    "If someone shares good news, match their excitement.",
    "Be curious, not impressive.",
    "Notice who makes you feel relaxed.",
    "You don’t have to attend everything you’re invited to.",
    "Apologize without explaining away the impact.",
    "Respect people’s time by being punctual.",
    "Small kindnesses are remembered.",
    "Don’t gossip to bond. It backfires.",
    "Ask before offering advice.",
    "Not everyone needs access to you.",
    "Follow up when you say you will.",
    "Let people finish their thoughts.",
    "Avoid turning conversations into competitions.",
    "Listen for what’s not being said.",
    "Don’t take quiet personally.",
    "Thank people for their time.",
    "Boundaries make relationships healthier.",
    "Speak clearly instead of hinting.",
    "Be honest without being harsh.",
    "Notice how people treat those who can’t help them.",
    "Give people space when emotions run high.",
    "You don’t need to win every discussion.",
    "Respect different communication styles.",
    "Remember details people share.",
    "Don’t overshare to force closeness.",
    "Kindness doesn’t need an audience.",
    "Silence can be supportive.",
    "Don’t assume intent. Ask.",
    "Notice who drains you consistently.",
    "Be present instead of interesting.",
    "If something bothers you, address it early.",
    "Don’t mock vulnerability.",
    "Say thank you often.",
    "Let people be themselves.",
    "You don’t owe everyone your energy.",
    "Choose honesty over avoidance.",
    "Respect differences without trying to fix them.",
    "Don’t talk over quieter voices.",
    "Ask how someone is really doing.",
    "Avoid sarcasm when emotions are involved.",
    "Validate feelings before facts.",
    "You don’t need to explain every boundary.",
    "Be generous with credit.",
    "Notice who celebrates your wins.",
    "Apologies work best when timely.",
    "Avoid passive-aggressive communication.",
    "People remember how you made them feel.",
    "Let conversations flow instead of controlling them.",
    "Respect when someone says no.",
    "Don’t pressure people to open up.",
    "Share attention, not just stories.",
    "Avoid assumptions based on tone alone.",
    "Check in on friends without an agenda.",
    "Keep private things private.",
    "Be clear instead of bureaucratic.",
    "Ask for clarification instead of reacting.",
    "Let friendships evolve naturally.",
    "Don’t compare relationships publicly.",
    "Give people the benefit of the doubt once.",
    "Avoid talking just to fill space.",
    "Notice patterns, not isolated moments.",
    "Choose connection over being right.",
    "Make room for different opinions.",
    "Be patient with communication differences.",
    "Don’t force chemistry.",
    "Be reliable. It builds trust quietly.",
    "Respect people’s comfort levels.",
    "Ask before changing plans.",
    "Listen more than you speak.",
    "Avoid bringing up sensitive topics casually.",
    "Give people time to respond.",
    "Don’t demand emotional labor.",
    "Check your tone when stressed.",
    "Celebrate others without comparison.",
    "Allow friendships to have seasons.",
    "Don’t assume silence equals distance.",
    "Be honest kindly.",
    "Respect personal space.",
    "Avoid public call-outs when private conversations work.",
    "Show appreciation regularly.",
    "Let people be themselves.",
    "Don’t expect mind-reading.",
    "Choose empathy first.",
    "Stay curious, not defensive.",
    "Avoid rushing closeness.",
    "Give grace where possible.",
    "Treat people the way you want to feel treated."
  ],
  [Category.Work]: [
    "Clarify expectations before starting the task.",
    "Write things down so your brain can rest.",
    "Don’t send messages when you’re frustrated. Draft first.",
    "Ask questions early. It saves time later.",
    "Protect your focus like it matters. It does.",
    "If it’s unclear, ask for clarification.",
    "Do the hard thing first when possible.",
    "Over-communicate progress, not excuses.",
    "Take breaks before burnout makes the decision for you.",
    "Close small tasks quickly. Momentum helps.",
    "Don’t multitask important work.",
    "Set boundaries around your availability.",
    "If you’re stuck, step away briefly.",
    "Prepare before meetings. It shows.",
    "Follow up conversations in writing.",
    "Keep your calendar realistic.",
    "If priorities change, confirm them.",
    "Don’t wait for perfection to share progress.",
    "Ask for feedback before the deadline.",
    "Respect other people’s time.",
    "Document decisions while they’re fresh.",
    "Don’t assume silence means approval.",
    "Communicate risks early.",
    "Block time for deep work.",
    "Keep task lists short and current.",
    "Say no when you’re at capacity.",
    "Prepare talking points before difficult conversations.",
    "Focus on outcomes, not just effort.",
    "If you miss a deadline, communicate quickly.",
    "Don’t carry work stress into every conversation.",
    "Learn to prioritize, not just execute.",
    "Keep meetings purposeful and brief.",
    "Clarify ownership before starting shared tasks.",
    "Avoid unnecessary urgency.",
    "Ask for context when tasks feel unclear.",
    "Track decisions so they don’t get revisited endlessly.",
    "Schedule breaks like meetings.",
    "Don’t take feedback personally. Use it.",
    "Protect time for thinking, not just doing.",
    "Follow through on commitments.",
    "Speak up when something isn’t sustainable.",
    "Align on definitions to avoid confusion.",
    "Don’t reply instantly if accuracy matters.",
    "Break large tasks into smaller steps.",
    "Keep stakeholders informed.",
    "Don’t overcommit to look helpful.",
    "Ask for help before you’re overwhelmed.",
    "Keep your workspace functional.",
    "Review priorities weekly.",
    "Rest improves productivity more than pushing harder.",
    "Don’t schedule back-to-back meetings all day.",
    "Write clear action items.",
    "Use checklists for repeatable tasks.",
    "Clarify deadlines in writing.",
    "Don’t assume others see your workload.",
    "Prepare agendas for meetings.",
    "Track progress visibly.",
    "Keep learning on the job.",
    "Pause before reacting to stressful messages.",
    "Protect your energy, not just your time.",
    "Ask why when tasks don’t make sense.",
    "Don’t confuse activity with impact.",
    "Summarize decisions at the end of meetings.",
    "Avoid last-minute rushes when possible.",
    "Set realistic timelines.",
    "Keep files organized.",
    "Share credit generously.",
    "Don’t hoard information.",
    "Review work before submitting.",
    "Build routines that support focus.",
    "Communicate delays early.",
    "Don’t personalize professional feedback.",
    "Clarify success criteria upfront.",
    "Use asynchronous communication when possible.",
    "Focus on what moves the work forward.",
    "Ask for feedback regularly.",
    "Keep goals visible.",
    "Avoid unnecessary complexity.",
    "Take notes during meetings.",
    "Don’t neglect documentation.",
    "Respect different working styles.",
    "Prepare for 1:1s thoughtfully.",
    "Don’t let small issues linger.",
    "Track your wins, not just tasks.",
    "Set boundaries around work hours.",
    "Don’t wait to ask for clarity.",
    "Improve processes when you can.",
    "Keep communication clear and concise.",
    "Don’t overwork to compensate for poor planning.",
    "Reflect on what worked after projects end.",
    "Focus on progress, not perfection.",
    "Don’t be afraid to say “I don’t know.”",
    "Build trust through consistency.",
    "Protect time for strategic thinking.",
    "Communicate priorities clearly.",
    "Ask for alignment when things shift.",
    "Don’t carry unnecessary tasks alone.",
    "Balance urgency with quality.",
    "Learn from mistakes without dwelling.",
    "Sustainable work beats short-term hustle."
  ],
  [Category.SelfCare]: [
    "Drink a full glass of water before checking your phone",
    "Open a window, even if just for two minutes",
    "Sit down while eating, even if it’s a snack",
    "Stretch your neck slowly before bed",
    "Wash your face without rushing",
    "Step outside without headphones for five minutes",
    "Change your bedsheets today, not tomorrow",
    "Take three deep breaths before replying to that message",
    "Clean one small surface, not the whole room",
    "Lower your shoulders right now",
    "Eat something warm",
    "Put your phone face down for ten minutes",
    "Moisturize your hands like they matter",
    "Go to bed 20 minutes earlier than usual",
    "Light a candle or turn on a soft lamp",
    "Sit somewhere comfortable on purpose",
    "Delete one app you don’t enjoy using",
    "Play music instead of scrolling",
    "Wash your cup immediately after using it",
    "Step away from the screen and blink slowly",
    "Take a shower without thinking about productivity",
    "Wear something comfortable even if no one will see you",
    "Drink water before coffee",
    "Rest your eyes by looking far away",
    "Say no without explaining too much",
    "Eat fruit today, even a small piece",
    "Pause and unclench your jaw",
    "Take off notifications for one hour",
    "Stretch your legs before sitting again",
    "Sit in silence for one minute",
    "Clean your phone screen",
    "Breathe in through your nose, out through your mouth",
    "Open your curtains fully",
    "Put on socks if your feet are cold",
    "Write down one thing bothering you",
    "Put that thought down for later",
    "Drink something warm slowly",
    "Take a short walk with no destination",
    "Wash your face before bed even if you’re tired",
    "Lower the volume a little",
    "Stop multitasking while eating",
    "Let yourself be bored for five minutes",
    "Stretch your fingers and wrists",
    "Sit up straighter, gently",
    "Delete one old message thread",
    "Step away from people for a moment",
    "Drink water after scrolling",
    "Take a deep breath before standing up",
    "Clean one drawer, not the whole room",
    "Touch something soft",
    "Put your phone away during meals",
    "Rest your eyes by closing them briefly",
    "Stand up and shake your arms",
    "Eat without watching anything",
    "Change into clean clothes",
    "Sit near natural light",
    "Drink water when you feel irritated",
    "Take a slower route if you can",
    "Exhale longer than you inhale",
    "Put your feet flat on the ground",
    "Wash your hands slowly",
    "Step outside just to feel the air",
    "Turn down background noise",
    "Stretch before reaching for your phone",
    "Put on a song you already love",
    "Notice where your body feels tense",
    "Relax your tongue from the roof of your mouth",
    "Drink water before sleeping",
    "Clean your pillowcase",
    "Let your shoulders drop",
    "Take a break before you feel exhausted",
    "Sit quietly after finishing a task",
    "Rub your temples gently",
    "Open your notes app and dump your thoughts",
    "Close unused tabs",
    "Eat something nourishing, not just convenient",
    "Stop scrolling when your eyes feel heavy",
    "Stand in the sun for a moment",
    "Stretch your back slowly",
    "Drink water before complaining",
    "Put your phone down during conversations",
    "Sit comfortably instead of “correctly”",
    "Wash your face with warm water",
    "Take one deep breath before responding",
    "Rest when you notice irritation",
    "Close your eyes and count to ten",
    "Clear your desk surface",
    "Eat one meal without distractions",
    "Slow down one action today",
    "Notice how your body feels sitting",
    "Turn off one unnecessary alert",
    "Drink water after waking up",
    "Take your time brushing your teeth",
    "Stretch before bed",
    "Sit somewhere quiet for a minute",
    "Put your phone away while walking",
    "Let your breathing slow naturally",
    "Clean something that’s been bothering you",
    "Give yourself permission to pause",
    "Do one small thing just because it feels good"
  ],
  [Category.Family]: [
    "Call a family member just to say hello",
    "Send a random photo from your day",
    "Ask how they’re really doing, then pause",
    "Sit with them without checking your phone",
    "Say thank you for something small they do",
    "Eat one meal together without screens",
    "Ask about a memory you’ve never heard",
    "Laugh at an old family joke",
    "Check in on the quiet one",
    "Hug them a second longer",
    "Apologize without adding explanations",
    "Ask for advice, even if you don’t need it",
    "Share good news, not just problems",
    "Sit next to them instead of across",
    "Put your phone away during conversations",
    "Help without being asked",
    "Say “I appreciate you” out loud",
    "Ask how their day actually went",
    "Listen without fixing",
    "Let a small thing slide",
    "Compliment something they don’t usually get praised for",
    "Sit in the same room doing separate things",
    "Share food instead of eating alone",
    "Ask about their plans for the week",
    "Say good morning properly",
    "Check in before assuming",
    "Laugh together at something silly",
    "Share a song you like",
    "Ask about something they care about",
    "Be patient with repetition",
    "Say “I hear you” before responding",
    "Sit and watch something together",
    "Let them finish their story",
    "Put effort into showing up",
    "Ask about their childhood",
    "Help with a chore quietly",
    "Say thank you for raising you",
    "Ask what they need today",
    "Offer help instead of advice",
    "Be present for five full minutes",
    "Send a voice note instead of a text",
    "Check in even when things feel fine",
    "Eat slowly together",
    "Share something you’re proud of them for",
    "Make eye contact while listening",
    "Ask how they feel, not just what happened",
    "Sit with them when they’re upset",
    "Don’t rush difficult conversations",
    "Say “I missed you”",
    "Let them be right sometimes",
    "Celebrate small wins together",
    "Ask before giving opinions",
    "Remember an important date",
    "Sit together in silence",
    "Share something you learned recently",
    "Be gentle when correcting",
    "Let them vent without interrupting",
    "Show interest in their routine",
    "Put effort into being kind",
    "Offer reassurance without dismissing feelings",
    "Share a meal you made",
    "Ask about their dreams",
    "Let go of winning the argument",
    "Spend time without an agenda",
    "Say “I love you” casually",
    "Make space for their emotions",
    "Sit with them during tough moments",
    "Acknowledge their effort",
    "Laugh about old stories",
    "Be patient with differences",
    "Ask what makes them happy lately",
    "Give compliments freely",
    "Be curious instead of defensive",
    "Help without expecting praise",
    "Say goodnight properly",
    "Share something that made you think of them",
    "Check in after a hard day",
    "Let them talk about the same thing again",
    "Be kind during disagreements",
    "Show up even when it’s inconvenient",
    "Ask what support looks like for them",
    "Respect boundaries even when it’s hard",
    "Choose peace over being right",
    "Sit closer when talking",
    "Appreciate their presence",
    "Say thank you for today",
    "Share laughter often",
    "Be slow to judge",
    "Remember you’re on the same side",
    "Put family time on purpose",
    "Ask how you can help more",
    "Let love show in small ways",
    "Speak gently when emotions run high",
    "Take interest in their world",
    "Make time even when busy",
    "Say “I’m glad you’re here”",
    "Choose patience today",
    "Give them the benefit of the doubt",
    "Be present, not perfect",
    "Show love in ways they understand"
  ],
  [Category.DailyHabits]: [
    "Drink a glass of water after waking up",
    "Make your bed loosely, not perfectly",
    "Open a window or curtain",
    "Stretch for one minute",
    "Wash your face properly",
    "Eat something before caffeine",
    "Step outside briefly",
    "Check your posture",
    "Take three deep breaths",
    "Write down one thing to do today",
    "Clean one small surface",
    "Respond to one message you’ve been avoiding",
    "Take a short walk",
    "Sit without your phone for five minutes",
    "Drink water mid-morning",
    "Stand up and move your body",
    "Look away from screens every hour",
    "Eat slowly for one meal",
    "Wash your cup after using it",
    "Lower your shoulders",
    "Tidy one small area",
    "Pause before reacting",
    "Drink water before lunch",
    "Take a moment of silence",
    "Stretch your neck and shoulders",
    "Close unused tabs",
    "Check in with how you feel",
    "Take a deep breath before replying",
    "Sit up straighter",
    "Put your phone down during meals",
    "Step outside again in the afternoon",
    "Drink water instead of another snack",
    "Finish one small task completely",
    "Rest your eyes for a minute",
    "Stand up after long sitting",
    "Wash your hands slowly",
    "Breathe deeply once an hour",
    "Say thank you to someone",
    "Do one thing without multitasking",
    "Notice tension in your body",
    "Drink water when you feel tired",
    "Take a short stretch break",
    "Read a few pages of anything",
    "Eat fruit or something fresh",
    "Clean your phone screen",
    "Check your breathing",
    "Organize one digital file",
    "Sit near natural light",
    "Relax your jaw",
    "Take a moment to pause",
    "Move your body gently",
    "Drink water mid-afternoon",
    "Do one helpful thing for someone",
    "Slow down one activity",
    "Finish what you start",
    "Stretch your legs",
    "Take a few deep breaths",
    "Lower background noise",
    "Stand outside for fresh air",
    "Drink water before dinner",
    "Eat dinner without distractions",
    "Tidy up after eating",
    "Reflect on one thing you did well",
    "Put things back where they belong",
    "Prepare something for tomorrow",
    "Wash your face in the evening",
    "Stretch lightly before bed",
    "Turn down bright lights",
    "Charge your phone before sleeping",
    "Put your phone away for the night",
    "Take a deep breath before sleep",
    "Go to bed at a reasonable time",
    "Notice what your body needs",
    "Let one thing go",
    "Drink water before sleeping",
    "Slow your breathing",
    "Sit quietly for one minute",
    "Close your eyes briefly",
    "Acknowledge today’s effort",
    "Relax your shoulders again",
    "Choose one priority tomorrow",
    "Lay out clothes or items",
    "Tidy one last thing",
    "Say goodnight to someone",
    "Breathe deeply before sleep",
    "Release tension in your body",
    "Let your thoughts slow",
    "Appreciate something small",
    "Rest without guilt",
    "Allow yourself to pause",
    "Wake up gently tomorrow",
    "Drink water first thing",
    "Stretch when you wake",
    "Start the day calmly",
    "Take things one step at a time",
    "Move with intention",
    "Breathe before reacting",
    "End the day consciously",
    "Be kind to yourself today",
    "Repeat what worked"
  ],
  [Category.Friends]: [
    "Text first sometimes",
    "Reply even if it’s late",
    "Send a meme that reminded you of them",
    "Ask how they’re really doing",
    "Show up when you say you will",
    "Check in without a reason",
    "Listen without interrupting",
    "Celebrate their wins loudly",
    "Sit with them during quiet moments",
    "Remember something important they said",
    "Ask before giving advice",
    "Be honest gently",
    "Laugh at their bad jokes",
    "Put your phone away when hanging out",
    "Send a voice note instead of texting",
    "Follow up after a hard day",
    "Ask about their goals",
    "Let them vent without fixing",
    "Keep their secrets",
    "Make time, not excuses",
    "Compliment something specific",
    "Apologize when you mess up",
    "Be patient with their flaws",
    "Invite them even if they might say no",
    "Share your thoughts honestly",
    "Check in when they go quiet",
    "Support them publicly",
    "Show appreciation out loud",
    "Laugh together often",
    "Ask what they need",
    "Be reliable",
    "Let them change",
    "Listen more than you talk",
    "Show up on ordinary days",
    "Remember birthdays without reminders",
    "Sit next to them, not across",
    "Make eye contact while listening",
    "Encourage their growth",
    "Give space without disappearing",
    "Be present for five full minutes",
    "Share good news with them",
    "Ask about something they care about",
    "Forgive small mistakes",
    "Be clear instead of passive",
    "Keep plans simple",
    "Say thank you",
    "Check in after disagreements",
    "Let go of being right",
    "Support their boundaries",
    "Choose kindness during conflict",
    "Send a “thinking of you” message",
    "Laugh at old memories",
    "Respect their time",
    "Ask before assuming",
    "Be curious, not judgmental",
    "Help when you can",
    "Show up emotionally",
    "Ask how you can support them",
    "Share food",
    "Be patient with distance",
    "Make space for different opinions",
    "Be honest about your feelings",
    "Don’t keep score",
    "Sit in comfortable silence",
    "Reach out even when busy",
    "Let conversations flow naturally",
    "Celebrate small milestones",
    "Be generous with encouragement",
    "Show interest in their life",
    "Let them be themselves",
    "Laugh at yourself together",
    "Be gentle when correcting",
    "Check in during tough times",
    "Give compliments freely",
    "Make time without an agenda",
    "Accept their growth",
    "Respect changes in routine",
    "Say “I miss you”",
    "Keep things light sometimes",
    "Take things less personally",
    "Show up when it matters",
    "Be consistent",
    "Let go of grudges",
    "Ask about their day",
    "Appreciate the friendship",
    "Don’t disappear without explanation",
    "Be understanding",
    "Keep communication open",
    "Choose empathy",
    "Make effort without expecting returns",
    "Celebrate who they are now",
    "Be kind in small moments",
    "Stay connected in simple ways",
    "Support them quietly",
    "Let them lead sometimes",
    "Be present during conversations",
    "Accept imperfections",
    "Keep checking in",
    "Show love in your own way",
    "Choose friendship today"
  ],
  [Category.DigitalLife]: [
    "Turn off notifications you don’t need",
    "Put your phone face down while working",
    "Unfollow accounts that make you feel bad",
    "Mute group chats temporarily",
    "Charge your phone before bed",
    "Clean your home screen",
    "Delete one unused app",
    "Turn off push notifications for social media",
    "Lower your screen brightness at night",
    "Close extra browser tabs",
    "Log out of an account you don’t use",
    "Turn off read receipts if they stress you",
    "Set a quiet hour for messages",
    "Put your phone in another room briefly",
    "Remove apps from your home screen",
    "Use do not disturb intentionally",
    "Unsubscribe from one mailing list",
    "Clean your downloads folder",
    "Turn off autoplay",
    "Use a darker theme at night",
    "Take a break after long scrolling",
    "Stop doom-scrolling when you notice it",
    "Mute keywords that stress you",
    "Turn off sound effects",
    "Check messages at set times",
    "Close social apps after posting",
    "Avoid checking stats repeatedly",
    "Hide follower counts if possible",
    "Delete screenshots you don’t need",
    "Clean your desktop icons",
    "Log out of social media before sleeping",
    "Take your phone off the bed",
    "Remove apps that drain your mood",
    "Silence non-urgent chats",
    "Turn off vibration alerts",
    "Keep work apps off personal time",
    "Clear your browser history occasionally",
    "Rename messy files",
    "Reduce background apps",
    "Disable unnecessary permissions",
    "Set screen limits intentionally",
    "Keep notifications minimal",
    "Don’t reply immediately if you don’t want to",
    "Take screenshots less often",
    "Log out instead of deleting apps temporarily",
    "Use folders to reduce clutter",
    "Turn off email notifications",
    "Check social media with intention",
    "Put your phone away while eating",
    "Reduce tab hoarding",
    "Clean your contact list",
    "Archive old chats",
    "Turn off pop-ups",
    "Lower app badges",
    "Remove widgets you don’t use",
    "Silence apps that interrupt focus",
    "Use airplane mode briefly",
    "Delete old voice notes",
    "Stop watching autoplay videos",
    "Close apps after use",
    "Back up important files",
    "Rename photos meaningfully",
    "Log out of shared devices",
    "Review app permissions",
    "Turn off location tracking when not needed",
    "Reduce notifications before sleep",
    "Keep your lock screen simple",
    "Hide distracting apps",
    "Set a no-phone window",
    "Clear your clipboard",
    "Stop checking messages mid-task",
    "Close apps before switching tasks",
    "Don’t open every notification immediately",
    "Turn off previews on your lock screen",
    "Take breaks from group chats",
    "Reduce digital noise intentionally",
    "Delete apps you only scroll",
    "Turn off auto-downloads",
    "Mute stories temporarily",
    "Check emails less often",
    "Clean your notes app",
    "Archive instead of deleting when unsure",
    "Turn off unnecessary syncing",
    "Reduce background refresh",
    "Pause before replying online",
    "Avoid reading comments when tired",
    "Don’t multitask across apps",
    "Stop refreshing feeds repeatedly",
    "Log out of accounts you no longer need",
    "Keep digital spaces calm",
    "Use tech to support, not stress",
    "Choose quiet over constant updates",
    "Let messages wait sometimes",
    "Keep your digital life intentional",
    "Reduce scrolling before sleep",
    "Close apps at the end of the day",
    "Turn off your phone earlier tonight",
    "Let your mind rest offline",
    "Create space between you and screens",
    "Treat your attention like it matters"
  ],
};

export const ALL_ADVICE = Object.values(ADVICE_DATABASE).flat();
