import { Category, AdviceData } from './types';

export const CATEGORY_EMOJI_CODES: Record<Category, string> = {
  [Category.Finance]: "1f4b8",
  [Category.Love]: "1f498",
  [Category.Health]: "1f9d8",
  [Category.Social]: "1f942",
  [Category.Work]: "1f4bc",
  [Category.SelfCare]: "1f6c1",
  [Category.Family]: "1f3e1",
  [Category.DailyHabits]: "1f5d3-fe0f",
  [Category.Friends]: "1f46f",
  [Category.DigitalLife]: "1f4f1",
};

export const ADVICE_DATABASE: AdviceData = {
  [Category.Finance]: [
    "Check your subscriptions once a month. One of them is stealing from you.",
    "Don’t shop online when you’re bored. That’s how regret gets delivered.",
    "If you can’t buy it twice, think longer before buying it once.",
    "Unsubscribe before you forget why you signed up.",
    "Track your spending for one week. You’ll spot the leak immediately.",
    "Cheap chargers always fail at the worst time. Spend a little more.",
    "Avoid impulse buys after midnight. Nothing good happens after midnight.",
    "Set spending limits before you feel rich.",
    "Sales are only savings if you planned to buy it anyway.",
    "Delete shopping apps you only use when you’re stressed.",
    "Check bank statements like you check social media. Regularly.",
    "Don’t loan money you’ll resent not getting back.",
    "Keep an emergency fund even if it grows slowly.",
    "Pause before tapping “Buy now”. Even 10 seconds helps.",
    "Avoid lifestyle upgrades that lock you into higher monthly bills.",
    "Don’t compare your salary to someone else’s highlight reel.",
    "If a deal feels rushed, walk away.",
    "Buy quality for things you use every day.",
    "Review your subscriptions on your birthday. Make it a ritual.",
    "Money saved quietly is still money saved.",
    "Avoid financial decisions when you’re emotional.",
    "Pay yourself first, even if it’s small.",
    "Set reminders for bills so fees don’t sneak up on you.",
    "Don’t keep unused cards “just in case”.",
    "If it requires a payment plan, think twice.",
    "Track expenses before setting strict budgets. Awareness comes first.",
    "Avoid shopping as entertainment.",
    "Cancel trials immediately after signing up.",
    "Don’t keep money goals vague. Numbers matter.",
    "Raise your savings when your income increases, not your lifestyle.",
    "Avoid lending money to fix guilt.",
    "Save windfalls before spending them.",
    "Revisit old subscriptions you forgot existed.",
    "If you dread checking your balance, that’s your cue.",
    "Avoid expensive habits that don’t bring daily value.",
    "Plan big purchases in advance. Anticipation beats regret.",
    "Don’t shop hungry, tired, or bored.",
    "Keep a “fun money” limit to avoid guilt spending.",
    "Stop paying for convenience you don’t need.",
    "Automate savings so you don’t negotiate with yourself.",
    "If it needs constant maintenance, it costs more than you think.",
    "Review your spending categories every few months.",
    "Keep receipts for big purchases until you’re sure.",
    "Avoid subscriptions that rely on forgetfulness.",
    "Money anxiety often comes from not knowing the numbers.",
    "Set clear savings goals, not vague intentions.",
    "Don’t upgrade something that still works fine.",
    "Avoid emotional shopping after bad days.",
    "If it doesn’t fit your budget now, it won’t fit later.",
    "Re-evaluate recurring payments quarterly.",
    "Spending less can feel better than earning more.",
    "Avoid flashy investments you don’t understand.",
    "Keep separate accounts for saving and spending.",
    "Small daily expenses add up faster than you think.",
    "Don’t ignore fees. They quietly compound.",
    "Financial discipline beats motivation.",
    "Budget for joy, not just survival.",
    "Track money weekly, not yearly.",
    "Avoid impulse upgrades pushed by “limited time” banners.",
    "Keep emergency money boring and accessible.",
    "If you can’t explain the purchase, don’t make it.",
    "Don’t shop to impress people who won’t notice.",
    "Compare prices before loyalty kicks in.",
    "Avoid buying things to fix boredom.",
    "Save for future peace, not future stress.",
    "Review subscriptions every season change.",
    "Avoid spending money to escape uncomfortable emotions.",
    "Know your fixed costs by heart.",
    "Financial clarity reduces anxiety more than extra income.",
    "Spend intentionally, not reactively.",
    "Delay purchases that excite you too quickly.",
    "Track cash leaks, not just big expenses.",
    "Avoid “treat yourself” spirals.",
    "Check return policies before buying.",
    "Separate wants from timing. You can want it later.",
    "Set a monthly money check-in with yourself.",
    "Avoid upgrades that don’t solve real problems.",
    "Stop paying for tools you don’t use.",
    "Revisit your financial goals when life changes.",
    "Avoid debt for things that lose value quickly.",
    "Save before spending, not after.",
    "Watch your money habits during stressful weeks.",
    "Avoid keeping cards linked to unused services.",
    "If you forget what you bought, you didn’t need it.",
    "Money saved is future flexibility.",
    "Avoid impulse purchases disguised as “self-care”.",
    "Don’t normalize small overdraft fees.",
    "Set spending alerts to stay aware.",
    "Reduce recurring costs before chasing extra income.",
    "Avoid buying trends you won’t love long-term.",
    "Track expenses by category to spot patterns.",
    "Avoid financial advice that promises shortcuts.",
    "Plan purchases, don’t chase deals.",
    "Keep financial goals visible, not hidden.",
    "Money habits matter more than money moments.",
    "Cancel services you haven’t used in 30 days.",
    "Avoid spending to fill emotional gaps.",
    "Review financial goals every quarter.",
    "Spend money where it truly improves your daily life.",
    "Financial peace comes from clarity, not perfection."
  ],
  [Category.Love]: [
    "Don’t text when you’re hungry, tired, or already annoyed.",
    "If they confuse you often, that’s information.",
    "Pay attention to how you feel after spending time with them.",
    "Ask questions you’re afraid of the answers to.",
    "Consistency matters more than intensity.",
    "Don’t chase mixed signals. Clarity is kinder.",
    "If they only show up late at night, notice that pattern.",
    "Say what you mean instead of hoping they guess.",
    "Chemistry fades if communication doesn’t follow.",
    "Don’t stay just because you’ve already stayed this long.",
    "How they handle small conflicts matters more than big promises.",
    "Don’t explain your needs like you’re apologizing.",
    "If you feel lonely with them, that’s not a good sign.",
    "Attraction grows where respect lives.",
    "Stop rereading old messages. They won’t change.",
    "Love shouldn’t feel like a performance review.",
    "If effort disappears after commitment, talk about it.",
    "Notice how they talk about people they used to love.",
    "Don’t ignore your body’s reactions. They’re honest.",
    "Choose someone who listens without planning their reply.",
    "Don’t rush closeness to avoid loneliness.",
    "Pay attention to actions, not explanations.",
    "If you’re always adjusting, ask why.",
    "Love shouldn’t make you shrink.",
    "Ask for what you need, not what you think they’ll accept.",
    "If you feel anxious most of the time, pause.",
    "Don’t confuse familiarity with safety.",
    "How someone handles boundaries tells you a lot.",
    "You shouldn’t have to earn basic kindness.",
    "Love grows when both people feel seen.",
    "Don’t stay silent to keep the peace.",
    "If you’re scared to bring things up, notice that.",
    "Pay attention to how they show care on ordinary days.",
    "Love isn’t proven through endurance.",
    "Choose someone who makes repairs after mistakes.",
    "Don’t settle because you’re tired of starting over.",
    "Your needs are not “too much.”",
    "Don’t romanticize emotional unavailability.",
    "Healthy love feels calm more often than chaotic.",
    "Trust builds slowly and breaks quickly.",
    "If you feel like you’re competing for attention, stop.",
    "Ask how they imagine the future. Listen closely.",
    "Love shouldn’t require constant reassurance.",
    "Notice whether conflict leads to growth or distance.",
    "Don’t ignore red flags because they wave politely.",
    "Choose honesty over harmony.",
    "Love is mutual effort, not mutual exhaustion.",
    "If they dismiss your feelings, believe them.",
    "Don’t wait for someone to change who hasn’t tried.",
    "You deserve enthusiasm, not tolerance.",
    "Attraction without respect won’t last.",
    "Love shouldn’t feel like guessing.",
    "If you feel calmer alone, ask why.",
    "Don’t confuse potential with reality.",
    "Healthy love allows room for individuality.",
    "Pay attention to how disagreements end.",
    "Choose someone who’s curious about your inner world.",
    "Love grows where accountability lives.",
    "If you’re afraid to be yourself, something’s off.",
    "Don’t stay because you’re scared of being alone.",
    "Love shouldn’t feel like walking on eggshells.",
    "Notice how they respond when you’re vulnerable.",
    "If they avoid difficult conversations, that matters.",
    "Love thrives on mutual respect, not power imbalance.",
    "Don’t ignore your intuition to keep hope alive.",
    "Choose growth over comfort.",
    "Love should feel supportive, not draining.",
    "If communication feels one-sided, it probably is.",
    "Don’t stay where effort feels conditional.",
    "Love is shown in follow-through.",
    "Don’t beg for attention that should be given freely.",
    "If they don’t make time, they’re making a choice.",
    "Love shouldn’t require constant explanation of your worth.",
    "Notice whether you feel valued or evaluated.",
    "Choose emotional safety over excitement.",
    "Love grows through repair, not perfection.",
    "If they invalidate your feelings, don’t minimize that.",
    "Love shouldn’t feel like survival.",
    "Choose someone who communicates, not disappears.",
    "If it hurts more than it heals, pause.",
    "Love doesn’t demand you abandon yourself.",
    "Pay attention to patterns, not apologies.",
    "Healthy love includes boundaries."
  ],
  [Category.Health]: [
    "Drink a glass of water before you drink anything else in the morning.",
    "If you’re stuck on a problem, go for a 10-minute walk. Alone.",
    "Stretch while your coffee brews. You won’t do it later.",
    "Your brain needs a break from inputs. Leave the phone behind sometimes.",
    "If you can’t sleep, get out of bed. Your bed is for sleep, not for worry.",
    "Small movements count. Take the stairs.",
    "Rest is not a reward. It’s a requirement.",
    "If your body hurts, it’s talking to you. Listen.",
    "Nature is a reset button. Find a tree.",
    "Don’t wait until you’re exhausted to stop.",
    "Breathe into your stomach, not your chest.",
    "Your posture affects your mood. Sit up for one minute.",
    "Sunlight in the morning sets your clock. Step outside.",
    "If you’re overwhelmed, focus on your next breath.",
    "Healthy is a practice, not a destination.",
    "Give your eyes a break from the screen every 20 minutes.",
    "Sleep is the foundation of everything else.",
    "Don’t ignore the small signs of burnout.",
    "Hydration solves more problems than you think.",
    "Eat slowly. Your brain needs time to catch up.",
    "Movement should feel like a celebration, not a punishment.",
    "Take your shoes off and touch the grass.",
    "A cold shower can reset a racing mind.",
    "Don’t skip your routine when life gets busy. That’s when you need it most.",
    "Your worth is not tied to your productivity.",
    "Allow yourself to do nothing for five minutes.",
    "Practice gratitude for what your body can do today.",
    "Consistency beats intensity in health.",
    "Listen to your hunger, not just the clock.",
    "Forgive yourself for the days you can’t give 100%.",
    "Mental health is just health. Treat it that way.",
    "Create a wind-down ritual before bed.",
    "Protect your peace like it’s your most valuable asset.",
    "Focus on one thing at a time.",
    "It’s okay to say no to things that drain you.",
    "Spend time with people who make you feel light.",
    "Learn to recognize your stress triggers.",
    "Quality sleep is better than extra hours of work.",
    "Your health is an investment, not an expense.",
    "Slow down. You’re not in a race.",
    "Deep breathing is the fastest way to calm your nervous system.",
    "Don’t wait for a crisis to take care of yourself.",
    "Small habits lead to big changes.",
    "Treat your future self with kindness.",
    "Movement is medicine.",
    "Prioritize your well-being over external expectations.",
    "Learn to sit with your emotions without judging them.",
    "Health is wealth you can’t buy back later.",
    "Focus on what you can control.",
    "Be gentle with yourself. You’re doing your best."
  ],
  [Category.Social]: [
    "Listen twice as much as you speak. You’ll learn twice as much.",
    "If you think something nice about someone, say it. Immediately.",
    "Put your phone away when someone is talking to you. It’s a superpower.",
    "RSVP as soon as you know. It’s the kindest thing for the host.",
    "Don’t complain about things you aren’t willing to change.",
    "Admit when you’re wrong. It builds trust faster than being right.",
    "A small gift with no occasion is the best kind of gift.",
    "Ask more than you tell.",
    "Be the person who remembers the small details.",
    "Don’t gossip. It tells people you’ll gossip about them too.",
    "Show up on time. It says you respect their time.",
    "If you’re invited, someone wants you there. Try to go.",
    "Comfort is the enemy of connection. Be a little brave.",
    "Say thank you like you mean it.",
    "Give people your full attention. It’s rare and valuable.",
    "Ask follow-up questions. It shows you were listening.",
    "Don’t interrupt. Wait for the breath.",
    "Offer help before being asked.",
    "Notice the person who’s being quiet. Include them.",
    "Be genuinely happy for others’ success.",
    "Vulnerability is the bridge to deep connection.",
    "Don’t take things personally. It’s usually not about you.",
    "Practice active listening.",
    "Apologize without the “but”.",
    "Find common ground before highlighting differences.",
    "Be curious about people’s stories.",
    "A smile is a universal invitation.",
    "Celebrate small wins with your friends.",
    "Protect your friends’ secrets.",
    "Keep your promises, especially the small ones.",
    "Be the person people feel safe around.",
    "Acknowledge people’s efforts, even if they fail.",
    "Don’t make everything about yourself.",
    "Respect people’s boundaries without questioning them.",
    "Be kind to everyone, not just those who can help you.",
    "Practice empathy daily.",
    "Learn people’s names and use them.",
    "Give credit where it’s due.",
    "Be a bridge-builder, not a wall-builder.",
    "Offer encouragement freely.",
    "Listen to understand, not to respond.",
    "Be present in the conversation.",
    "Avoid judgmental language.",
    "Find the good in everyone you meet.",
    "Be the first to reach out.",
    "Don’t overpromise.",
    "Value quality over quantity in your social circle.",
    "Be yourself. Everyone else is taken.",
    "Show up for the people who show up for you.",
    "Leave people better than you found them."
  ],
  [Category.Work]: [
    "Your job will be posted before your obituary. Don’t over-sacrifice.",
    "If it takes less than two minutes, do it now.",
    "Turn off notifications when you’re doing deep work.",
    "Close your laptop at the end of the day. Really close it.",
    "Don’t reply to emails that make you angry until tomorrow.",
    "Protect your calendar. If you don’t, someone else will fill it.",
    "Lunch is for eating, not for working.",
    "A messy desk is a messy mind. Clear it once a week.",
    "Saying no to one thing is saying yes to your priorities.",
    "Focus on output, not hours.",
    "Don’t confuse busy with productive.",
    "Set boundaries early. It’s harder to set them later.",
    "Take your vacation days. All of them.",
    "Learn to delegate. You can’t do it all.",
    "Ask for feedback before you think you’re finished.",
    "Keep a list of your wins. You’ll need it for reviews.",
    "Networking is just making friends with common interests.",
    "Find a mentor, then be a mentor.",
    "Communication is your most valuable skill.",
    "Don’t be afraid to ask “dumb” questions.",
    "Learn to say “I don’t know, but I’ll find out.”",
    "Protect your energy as much as your time.",
    "Done is better than perfect.",
    "Set clear goals for every meeting.",
    "Take regular breaks. Your brain needs them.",
    "Don’t take work criticism personally.",
    "Be reliable. It’s the best reputation to have.",
    "Learn to manage up.",
    "Focus on what matters, ignore the noise.",
    "Your career is a marathon, not a sprint.",
    "Celebrate milestones, not just the finish line.",
    "Be kind to the people you work with.",
    "Stay curious and keep learning.",
    "Don’t settle for a toxic environment.",
    "Know your worth and advocate for it.",
    "Balance is something you create, not something you find.",
    "Listen more than you talk in meetings.",
    "Be a problem-solver, not a problem-finder.",
    "Keep your promises to your colleagues.",
    "Your identity is more than your job title.",
    "Find joy in the process, not just the result.",
    "Take ownership of your mistakes.",
    "Be the person who gets things done.",
    "Value your time and respect others’ time.",
    "Stay professional, even in difficult situations.",
    "Focus on building long-term relationships.",
    "Don’t be afraid to take risks.",
    "Trust your intuition.",
    "Keep a healthy perspective on work stress.",
    "Remember why you started."
  ],
  [Category.SelfCare]: [
    "Forgive yourself for what you didn’t know then.",
    "Say no without explaining why. You don’t owe a reason.",
    "Buy the comfortable shoes. Your mood starts at your feet.",
    "Stop following people who make you feel like you aren’t enough.",
    "Tidy your space before you go to sleep. Your future self will thank you.",
    "It’s okay to change your mind. That’s called growth.",
    "Write it down. Your brain is for having ideas, not holding them.",
    "Be your own best friend.",
    "Celebrate your own progress, no matter how small.",
    "You are allowed to take up space.",
    "Practice self-compassion daily.",
    "Set boundaries that protect your peace.",
    "Listen to your inner voice.",
    "Treat yourself with the same kindness you give others.",
    "Acknowledge your feelings without judgment.",
    "Make time for things that make you happy.",
    "You don’t have to be perfect to be worthy.",
    "Disconnect to reconnect with yourself.",
    "Prioritize your needs.",
    "Learn to enjoy your own company.",
    "Invest in your own growth.",
    "Trust yourself.",
    "Allow yourself to rest without guilt.",
    "Celebrate your uniqueness.",
    "Focus on what you love about yourself.",
    "Be patient with your own progress.",
    "Create a space that feels like home.",
    "Forgive yourself for your mistakes.",
    "Practice mindfulness.",
    "Give yourself permission to slow down.",
    "Believe in your own potential.",
    "Focus on your own journey, not others’.",
    "Be gentle with your thoughts.",
    "Acknowledge your strengths.",
    "Take care of your future self.",
    "Say kind things to yourself.",
    "Allow yourself to feel all your emotions.",
    "Invest in your well-being.",
    "Your needs are valid.",
    "Be proud of who you are becoming.",
    "Find beauty in the ordinary.",
    "Protect your time.",
    "Make self-care a non-negotiable.",
    "Listen to what your soul needs.",
    "You are enough, exactly as you are.",
    "Take a deep breath and let go of what you can’t control.",
    "Nourish your body and mind.",
    "Create a life you don’t need an escape from.",
    "Be the love of your own life.",
    "Stay true to yourself."
  ],
  [Category.Family]: [
    "Ask your elders their stories while they are still here to tell them.",
    "Don’t let old roles define your new self. You can change.",
    "Eat together when you can. Without screens.",
    "Forgiveness is a gift you give yourself, not just them.",
    "Be the one who reaches out. It doesn’t matter whose turn it is.",
    "Family is what you build, not just what you’re born into.",
    "Show up for the big moments and the small ones.",
    "Listen to understand, not to argue.",
    "Respect your parents as individuals, not just roles.",
    "Create your own traditions.",
    "Boundaries are necessary for healthy family relationships.",
    "Tell them you love them, even if it feels awkward.",
    "Patience is the greatest gift you can give your family.",
    "Don’t bring up old grievances in new arguments.",
    "Focus on the present, not the past.",
    "Celebrate each other’s successes.",
    "Be the peacemaker when you can.",
    "Value your siblings as your lifelong friends.",
    "Make time for one-on-one connection.",
    "Apologize when you’re wrong.",
    "Support each other through the hard times.",
    "Learn from your family’s history.",
    "Don’t try to change them, love them as they are.",
    "Create a safe space for honesty.",
    "Be grateful for your roots.",
    "Invest in your family relationships.",
    "Stay connected, even across distances.",
    "Honor your ancestors.",
    "Be a positive influence in your family.",
    "Protect your family’s peace.",
    "Listen to the wisdom of your elders.",
    "Encourage the younger generation.",
    "Forgive the small things.",
    "Cherish the time you have together.",
    "Be present during family gatherings.",
    "Communicate openly and honestly.",
    "Respect each other’s privacy.",
    "Be kind to each other.",
    "Show appreciation for the little things.",
    "Focus on the love that binds you.",
    "Celebrate your family’s unique story.",
    "Be the one who breaks negative cycles.",
    "Value your family’s support.",
    "Stay curious about each other’s lives.",
    "Make memories that will last a lifetime.",
    "Offer help without being asked.",
    "Be a source of strength for your family.",
    "Respect each other’s differences.",
    "Trust your family.",
    "Love unconditionally."
  ],
  [Category.DailyHabits]: [
    "Make your bed. It’s the first win of the day.",
    "Write down three things you’re grateful for every night.",
    "Put your keys in the same place every single time.",
    "If you want to start a habit, start small. Ridiculously small.",
    "Don’t look at your phone for the first 30 minutes of the day.",
    "Prepare for tomorrow tonight.",
    "Stack your habits. Link new ones to old ones.",
    "Consistency is more important than intensity.",
    "Track your progress to stay motivated.",
    "Celebrate your streaks.",
    "Focus on the process, not just the result.",
    "Make it easy to do the right thing.",
    "Eliminate friction for good habits.",
    "Create friction for bad habits.",
    "Your environment shapes your habits.",
    "Start your day with intention.",
    "Review your goals daily.",
    "Keep your space organized.",
    "Practice mindfulness throughout the day.",
    "Learn to enjoy the routine.",
    "Consistency creates momentum.",
    "Don’t break the chain.",
    "Adjust your habits as your life changes.",
    "Focus on identity, not just outcomes.",
    "Be patient with yourself as you build new habits.",
    "Habits are the compound interest of self-improvement.",
    "Small wins add up over time.",
    "Focus on becoming the person you want to be.",
    "Replace bad habits with better ones.",
    "Visualize your success.",
    "Stay committed even when it’s hard.",
    "Learn from your setbacks.",
    "Keep your daily routine simple.",
    "Prioritize your most important tasks.",
    "Create a morning and evening ritual.",
    "Focus on one habit at a time.",
    "Make your habits visible.",
    "Stay consistent even on the weekends.",
    "Celebrate your habit milestones.",
    "Your habits define your future.",
    "Invest in your daily routine.",
    "Be disciplined but flexible.",
    "Focus on long-term growth.",
    "Habits are the foundation of success.",
    "Keep showing up every day.",
    "Success is hidden in your daily routine.",
    "Focus on progress, not perfection.",
    "Your habits create your reality.",
    "Stay focused on your goals.",
    "Commit to your daily habits."
  ],
  [Category.Friends]: [
    "Check in even when you don’t know what to say",
    "Notice who always reaches out and return the energy",
    "Don’t wait for a crisis to show care",
    "Ask follow-up questions days later",
    "Sit with them when words won’t help",
    "Be honest before resentment builds",
    "Make room for their growth, even when it changes things",
    "Celebrate their wins without comparing",
    "Let silence be comfortable",
    "Defend them when they’re not in the room",
    "Learn how they prefer to be supported",
    "Don’t assume distance means disinterest",
    "Say what you appreciate while it’s still true",
    "Apologize early, not perfectly",
    "Be curious instead of reactive",
    "Remember what they’re nervous about",
    "Show interest in what excites them",
    "Respect their boundaries without taking it personally",
    "Let them be different from you",
    "Choose kindness when you’re tired",
    "Follow up on hard conversations",
    "Check in after big moments, good or bad",
    "Don’t weaponize old mistakes",
    "Be patient with their healing",
    "Make space for uncomfortable honesty",
    "Say “I don’t fully get it, but I’m here”",
    "Notice when they need encouragement, not solutions",
    "Protect their trust",
    "Let friendships evolve instead of forcing old versions",
    "Be present without multitasking",
    "Validate their feelings before sharing yours",
    "Don’t disappear when things get awkward",
    "Ask how you can show up better",
    "Remember the small details they share",
    "Offer reassurance without minimizing",
    "Give them room to vent without correcting",
    "Show up consistently, not dramatically",
    "Accept that effort won’t always be equal",
    "Don’t keep mental scorecards",
    "Allow friendships to breathe",
    "Speak up when something hurts instead of pulling away",
    "Be willing to grow together",
    "Respect their time as much as your own",
    "Say “I miss you” without expectation",
    "Learn their love language as a friend",
    "Celebrate who they are becoming",
    "Don’t punish them for being honest",
    "Let go of friendships that require shrinking",
    "Show grace when they’re overwhelmed",
    "Be slow to judge their choices",
    "Support their boundaries publicly and privately",
    "Give credit where it’s due",
    "Stay when conversations get real",
    "Notice when they’re carrying too much",
    "Ask how they’re coping, not just what’s happening",
    "Don’t ghost difficult feelings",
    "Be flexible as life changes",
    "Offer presence over perfection",
    "Trust them with your truth",
    "Let them rest without guilt",
    "Don’t expect them to read your mind",
    "Appreciate effort, not just results",
    "Ask what support looks like for them right now",
    "Hold space without rushing resolution",
    "Be gentle when correcting",
    "Let go of control in shared plans",
    "Speak with care when emotions are high",
    "Celebrate ordinary moments together",
    "Respect when they need distance",
    "Don’t confuse honesty with harshness",
    "Show up even when it’s inconvenient",
    "Let friendships change shape without resentment",
    "Say thank you more than you think you should",
    "Protect the friendship during conflict",
    "Be willing to listen twice",
    "Don’t assume intent; ask",
    "Value consistency over intensity",
    "Encourage them without pressure",
    "Make room for joy, not just support",
    "Be proud of how far they’ve come",
    "Keep communication clear and kind",
    "Choose understanding over winning",
    "Notice when they’re trying",
    "Let them be imperfect around you",
    "Say the hard things with care",
    "Don’t compare friendships",
    "Be a safe place, not a judge",
    "Show up emotionally, not just physically",
    "Respect their pace",
    "Keep choosing the friendship",
    "Trust takes time; protect it",
    "Let go of expectations you never shared",
    "Offer encouragement without conditions",
    "Be steady during their uncertainty",
    "Don’t take vulnerability lightly",
    "Appreciate who they are, not just what they give",
    "Allow room for forgiveness",
    "Be someone they don’t have to perform for",
    "Stay open even when it’s uncomfortable",
    "Treat friendship as something you actively care for"
  ],
  [Category.DigitalLife]: [
    "Unsubscribe from everything that doesn’t bring you joy or value.",
    "If you haven’t opened an app in a month, delete it.",
    "Don’t check your emails as soon as you wake up.",
    "Digital minimalism is a superpower in the modern world.",
    "Protect your attention like it’s your most valuable resource.",
    "Create digital-free zones in your home.",
    "Turn off non-essential notifications.",
    "Set time limits for social media apps.",
    "Organize your digital files regularly.",
    "Be intentional about who you follow online.",
    "Use technology to enhance your life, not replace it.",
    "Take regular digital detoxes.",
    "Back up your important data.",
    "Be mindful of your digital footprint.",
    "Practice digital etiquette.",
    "Protect your passwords and privacy.",
    "Use technology to connect with people, not just consume content.",
    "Learn to enjoy the silence away from screens.",
    "Be present in the real world.",
    "Set boundaries with your digital devices.",
    "Evaluate your digital habits regularly.",
    "Focus on quality over quantity in your digital life.",
    "Be a conscious consumer of digital content.",
    "Stay safe online.",
    "Use technology as a tool for creativity.",
    "Find balance in your digital life.",
    "Be mindful of the impact of technology on your mental health.",
    "Disconnect to reconnect with nature.",
    "Invest in real-world experiences.",
    "Your worth is not defined by your digital presence.",
    "Stay human in a digital world.",
    "Practice digital hygiene.",
    "Be intentional with your digital time.",
    "Value your attention and don’t give it away for free.",
    "Create a healthy relationship with technology.",
    "Don’t let digital devices distract you from the present moment.",
    "Be mindful of the source of your information.",
    "Protect your digital peace.",
    "Use technology to learn and grow.",
    "Stay connected to what truly matters.",
    "Be kind in your digital interactions.",
    "Limit your digital noise.",
    "Focus on deep work away from digital distractions.",
    "Be intentional about your digital consumption.",
    "Make time for real-world connections.",
    "Value your offline time.",
    "Be mindful of the ethics of technology.",
    "Stay curious about the impact of digital life.",
    "Create a digital life that serves you.",
    "Remember that the best moments are offline."
  ]
};