import { Category, AdviceData } from './types';

export const ADVICE_DATABASE: AdviceData = {
  [Category.Money]: [
    "Check your subscriptions once a month. One of them is stealing from you.",
    "Pay yourself first. Even if it's just $20.",
    "Never go grocery shopping when you are hungry.",
    "If you can't buy it twice, you can't afford it.",
    "Automate your savings so you never see the money leave.",
    "Spend money on experiences, not things.",
    "Sleep on big purchases for at least 24 hours.",
    "Invest in what you understand.",
  ],
  [Category.Romance]: [
    "Listen more than you speak.",
    "Never stop dating your partner.",
    "Apologize when you are wrong, not just to end the fight.",
    "Small gestures often mean more than grand ones.",
    "Love is a verb, not just a feeling.",
    "Don't expect your partner to read your mind.",
    "Be the partner you want to have.",
    "Respect is the foundation of affection.",
  ],
  [Category.Health]: [
    "Drink a glass of water first thing in the morning.",
    "Take the stairs whenever possible.",
    "Eat slowly and stop when you are 80% full.",
    "Sleep is the best performance enhancing drug.",
    "If you work at a desk, stand up every hour.",
    "Floss. Just do it.",
    "Wear sunscreen every single day.",
    "Listen to your body when it asks for rest.",
  ],
  [Category.Social]: [
    "Remember people's names. It makes them feel valued.",
    "Ask open-ended questions.",
    "Be genuinely interested in others.",
    "Don't look at your phone when someone is talking to you.",
    "Smile more often.",
    "Learn to say 'no' without explaining yourself.",
    "Give compliments freely, but honestly.",
    "Be on time. It shows respect.",
  ],
  [Category.Work]: [
    "Under-promise and over-deliver.",
    "Focus on one task at a time.",
    "Take breaks to recharge your creativity.",
    "Document your wins.",
    "Learn to delegate.",
    "Done is better than perfect.",
    "Networking is just making friends professionally.",
    "Ask for feedback before it's performance review time.",
  ],
  [Category.SelfCare]: [
    "Take time to be alone with your thoughts.",
    "Read a book for pleasure.",
    "Forgive yourself for past mistakes.",
    "It's okay to not be productive all the time.",
    "Set boundaries and stick to them.",
    "Treat yourself like you would treat a good friend.",
    "Disconnect to reconnect.",
    "Practice gratitude daily.",
  ],
  [Category.Family]: [
    "Call your parents just to say hello.",
    "Create traditions that last.",
    "Be present during family gatherings.",
    "Patience is the greatest gift you can give your family.",
    "Listen to your elders' stories.",
    "Support your siblings.",
    "Forgive family feuds; life is too short.",
    "Make time for family dinners.",
  ],
  [Category.DailyHabits]: [
    "Make your bed every morning.",
    "Write down your top 3 goals for the day.",
    "Read for 30 minutes before sleep.",
    "Declutter one small area every day.",
    "Keep a journal.",
    "Prepare for tomorrow tonight.",
    "Practice mindfulness while doing chores.",
    "Drink water before every meal.",
  ],
  [Category.Friends]: [
    "Check in on your strong friends.",
    "Celebrate your friends' wins as if they were your own.",
    "Be the friend who listens.",
    "Quality over quantity.",
    "Make time for face-to-face connection.",
    "Honesty is the best policy, even with friends.",
    "Reconnect with an old friend.",
    "Be reliable.",
  ],
  [Category.DigitalLife]: [
    "Turn off non-essential notifications.",
    "Unfollow accounts that make you feel bad about yourself.",
    "Charge your phone outside the bedroom.",
    "Take a digital detox once a week.",
    "Organize your digital files.",
    "Be mindful of what you share online.",
    "Use complex passwords.",
    "Remember that social media is a highlight reel.",
  ],
};

export const ALL_ADVICE = Object.values(ADVICE_DATABASE).flat();